### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by johntostring** [johntostring/spring-boot-shiro#3]

**Comment by shenzhanwei** [comment]
This application has no explicit mapping for /error, so you are seeing this as a fallback
提交验证的时候报错了

**Comment by shenzhanwei** [comment]
这个pom文件中的 <dependency>
            <groupId>com.millinch</groupId>
            <artifactId>spring-boot-shiro-starter</artifactId>
            <version>1.0.0</version>
        </dependency> 在 maven仓库中没有吗？

**Comment by johntostring** [comment]
@shenzhanwei Sorry，目前没有上传到 maven 仓库，需要自己 clone 到自己的电脑上 install 到本地仓库。

**Comment by shenzhanwei** [comment]
好的，感谢回复
